### ISSUE TITLE
Renombrar el nombre ViewController por InicioViewController

### ISSUE THREAD

**Issue by pedrohr99** [pedrohr99/MisPruebas#1]
Para renombrar el archivo hay que hacer los siguientes pasos:
1. En el inspector del proyecto, renombrar el archivo ViewController por InicioViewController.
2. En el storyboard, establecer como clase del view controller el nuevo nombre InicioViewController.

- [ ] En el inspector del proyecto, renombrar el archivo ViewController por InicioViewController.
- [ ] En el storyboard, establecer como clase del view controller el nuevo nombre InicioViewController.

**Comment by develop-github** [comment]
Voy a ponerme con este issue

**Comment by pedrohr99** [comment]
@develop-github Está todo correcto. Cierro este issue: close #1
